---
{{ $team := .Values.team -}}
---
{{ $repos := .Values.repositories -}}
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: "{{ $team.name }}-{{ $team.tier }}-users"
  namespace: openshift-gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: "{{ $team.name }}-{{ $team.tier }} users deployment apps"
  sourceRepos:
  {{- range $repos }}
    - {{ . | quote }}
  {{- end }}
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  destinations:
    - namespace: '*'
      server: "{{ $team.server }}"
    - namespace: "openshift-gitops"
      server: "https://kubernetes.default.svc"
  roles:
    # - name: users
    #   description: "Application teams privilleges for project `{{ $team.name }}-{{ $team.tier }}-users`"
    #   policies:
    #     - "p, proj:{{ $team.name }}-{{ $team.tier }}-users:users, applications, *, {{ $team.name }}-{{ $team.tier }}-users/*, allow"
    #   groups:
    #     - "AD.PAYMENTS.GROUP"
    # - name: users-deny
    #   description: "Application teams privilleges for project `{{ $team.name }}-{{ $team.tier }}-users`"
    #   policies:
    #     - "p, proj:{{ $team.name }}-{{ $team.tier }}-users:users, applications, *, {{ $team.name }}-{{ $team.tier }}  , deny"
    #   groups:
    #     - "AD.CLOUD.GROUP"
    # - name: admin
    #   description: "admin privilleges for project `{{ $team.name }}-{{ $team.tier }}-users`"
    #   policies:
    #     - "p, proj:{{ $team.name }}-{{ $team.tier }}-users:admin, applications, *, {{ $team.name }}-{{ $team.tier }}-admin/*, allow"
    #     - "p, proj:{{ $team.name }}-{{ $team.tier }}-users:admin, teams, get, {{ $team.name }}-{{ $team.tier }}-admin, allow"
    #   groups:
    #     - "AD.CLOUD.GROUP"