kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mssql-data
spec:
  storageClassName: {{ .Values.pvc.StorageClass }}
  accessModes:
  - {{ .Values.pvc.mssqldataaccessMode | quote}}
  resources:
    requests:
      storage: {{ .Values.pvc.mssqldbsize}}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mssql-userdb
spec:
  storageClassName: {{ .Values.pvc.StorageClass }}
  accessModes:
  - {{ .Values.pvc.userdbaccessMode | quote}}
  resources:
    requests:
      storage: {{ .Values.pvc.userdbsize}}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mssql-log
spec:
  storageClassName: {{ .Values.pvc.StorageClass }}
  accessModes:
   - {{ .Values.pvc.userlogaccessMode | quote}}
  resources:
    requests:
      storage: {{ .Values.pvc.userlogsize}}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mssql-temp
spec:
  storageClassName: {{ .Values.pvc.StorageClass }}
  accessModes:
   - {{ .Values.pvc.tempdbaccessMode | quote}}
  resources:
    requests:
      storage: {{ .Values.pvc.tempsize}}


