# Default values for mssql-latest.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
fullnameOverride: mssql-linux
replicas: 1

image:
  repository: mcr.microsoft.com/mssql/server
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "2019-latest"

ACCEPT_EULA:
    value: "y"
MSSQL_PID:
    value: "Developer"
MSSQL_AGENT_ENABLED:
    value: "true"
hostname: mssqllatest
sa_password: "Password01"
containers:
  ports:
      containerPort: 1433

podAnnotations: {}

podSecurityContext:
   fsGroup: 10001

service:
  type: ClusterIP
  port: 1433

pvc:
 StorageClass: managed-premium
 userdbaccessMode: ReadWriteOnce
 userdbsize: 1Gi
 userlogaccessMode: ReadWriteOnce
 userlogsize: 1Gi
 tempdbaccessMode: ReadWriteOnce
 tempsize: 1Gi
 mssqldataaccessMode: ReadWriteOnce
 mssqldbsize: 1Gi

anyuid:
  enabled: true
serviceAccount:
  create: false


