{{- if .Values.externalSecrets.enabled -}}
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "app-charts.fullname" . }}-aws-external-secret
  labels:
  {{- include "app-charts.labels" . | nindent 4 }}
spec:
  backendType: secretsManager
  data:
    {{- range $k, $v := .Values.externalSecrets.values}}
    - key: {{ $.Values.externalSecrets.awsName }}
      name: {{ $k }}
      property: {{ $v }}
    {{- end }}
{{- end }}