{{- if .Values.anyuid.enabled -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "mssql-latest.fullname" . }}:scc:anyuid
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:openshift:scc:anyuid
subjects:
- kind: ServiceAccount
  {{- if .Values.serviceAccount.create }}
  name: {{ include "mssql-latest.fullname" . }}
  {{ else }}
  name: default
  {{- end }}
{{- end }}
