microenvironments:
  - name: ob
    ignoreResourceQuota: true
    projects:
      - name: sm-cp
        labels: |
          name: ob-sm-cp
        serviceMeshControlPlane:
          targetRevision: "3.1.3"
          name: ob-sm-cp
          version: v2.2
          serviceMeshMemberRoll:
          - ob-dev
          - ob-sbox
          - ob-prd
          gateways:
            egress:
              enabled: true
            ingress:
          simpleCredentials:
            - frontend-credential

  - name: cloud
    ignoreResourceQuota: true
    projects:
      - name: infra
        labels: |
          name: cloud-infra

repositories:
  - https://gitlab.com/api/v4/projects/40182895/packages/helm/stable







