defaults:
  namespace: openshift-gitops
  server: https://kubernetes.default.svc
  repo: git@github.com:foster-rh/gitops.git
  helmRepo: "https://gitlab.com/api/v4/projects/40182895/packages/helm/stable"
  gitopsCoreVersion: 5.1.7
  
teams:
  - name: obt
    tier: nprd
    server: https://kubernetes.default.svc
    gitopsCoreVersion: 5.1.7
    adGroup: payments

  - name: obt
    tier: sbox
    server: https://kubernetes.default.svc
    gitopsCoreVersion: 5.1.7
    adGroup: payments

  - name: dvp
    tier: nprd
    server: https://kubernetes.default.svc
    gitopsCoreVersion: 5.1.7
    adGroup: cloud
