---
{{ $team := .Values.team -}}
---
{{ $defaults := .Values.defaults -}}
---
{{ range $pip := .Values.pipelinenamespace -}}
---
{{ range $ns := $pip.projects -}}
---
{{ range $pipelines := $ns.pipelines -}}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "{{ $team.name }}-{{ $team.tier }}-{{ $pip.name }}-{{ $ns.name }}-{{ $pipelines.name }}"
  annotations:
    argocd.argoproj.io/sync-wave: "75"
  namespace: openshift-gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: "{{ $team.name }}-{{ $team.tier }}-users"
  source:
    repoURL: "{{ $defaults.helmRepo }}"
    targetRevision: "{{ $pipelines.targetRevision }}"
    chart: "{{ $pipelines.chart }}"
    path: ""
    helm:
      values: |
        {{- toYaml $pipelines.values | nindent 8 }}
  destination:
    server: "{{ $team.server }}"
    {{- if not $pip.useNamespaceNameOnly }}
    namespace: {{ $pip.name }}-{{ $ns.name }}
    {{- else }}
    namespace: "{{ $ns.name }}"
    {{- end }}
  syncPolicy:
    automated:
      prune: false
    syncOptions:
      - Validate=false
      - CreateNamespace=false
    retry:
     limit: 1
     backoff:
       duration: 5s
       factor: 2 
       maxDuration: 3m
  ignoreDifferences:
---
{{ end }}
---
{{ end }}
---
{{ end }}
---
