---
{{ $values := .Values -}}
---
{{ range $ns := .Values.projects -}}
  {{- if $ns.pipeline_secrets }}
apiVersion: v1
kind: ServiceAccount
imagePullSecrets:
- name: registry-creds
metadata:
  name: build-bot
  namespace: "{{ $ns.name }}"
secrets:
  - name: ssh-key
  - name: registry-creds
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: build-bot:scc:anyuid
  namespace: "{{ $ns.name }}"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:openshift:scc:anyuid
subjects:
- kind: ServiceAccount
  name: build-bot
  namespace: "{{ $ns.name }}"
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: tekton-triggers-example-minimal
  namespace: "{{ $ns.name }}"
rules:
# Permissions for every EventListener deployment to function
- apiGroups: ["triggers.tekton.dev"]
  resources: ["eventlisteners", "triggerbindings", "triggertemplates", "triggers"]
  verbs: ["get"]
- apiGroups: [""]
  # secrets are only needed for Github/Gitlab interceptors
  resources: ["configmaps", "secrets"]
  verbs: ["get", "list", "watch"]
# Permissions to create resources in associated TriggerTemplates
- apiGroups: ["tekton.dev"]
  resources: ["pipelineruns", "pipelineresources", "taskruns"]
  verbs: ["create"]
- apiGroups: [""]
  resources: ["serviceaccounts"]
  verbs: ["impersonate"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  annotations:
    openshift.io/description: Allows builds in this namespace to push images to this
      namespace.  It is auto-managed by a controller; remove subjects to disable.
  name: tekton-triggers-example-minimal
  namespace: "{{ $ns.name }}"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: tekton-triggers-example-minimal
subjects:
- kind: ServiceAccount
  name: pipeline
  namespace: "{{ $ns.name }}"
---
  {{ end }}
{{ end }}
{{ range $ns := .Values.projects -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: view
  namespace: "{{ $ns.name }}"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: "{{ $values.adGroup }}"
---
{{ end }}