---
{{- range $k, $v := .Values.ingress }}
    {{- if eq (split "|" $v)._0 "allow-ns-to-ns" }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: ingress-local-allow-ns-to-ns-{{ (split "|" $v)._1 }}
spec:
  podSelector:
    matchLabels: {}
  policyTypes:
  - Ingress
  ingress:
  - ports:
    {{- range (split "&" (split "|" $v)._6) }}
    - protocol: TCP
      port: {{ . }}
    {{- end }}
    from:
    - namespaceSelector:
        matchLabels:
          {{ (split "|" $v)._2 }}: {{ (split "|" $v)._3 }}
      podSelector:
        matchLabels:
          {{ (split "|" $v)._4 }}: {{ (split "|" $v)._5 }}
---
  {{- end }}
{{- end }}
